apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: 241533151130.dkr.ecr.ap-southeast-1.amazonaws.com/gateway:latest  # Use local image
          imagePullPolicy: IfNotPresent  # Don't pull from Docker Hub
          ports:
            - containerPort: 80
