apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc  # Name of the PVC
spec:
  accessModes:
    - ReadWriteOnce  # This allows the volume to be mounted by a single node
  resources:
    requests:
      storage: 1Gi  # Request 1Gi of storage
