apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: 241533151130.dkr.ecr.ap-southeast-1.amazonaws.com/service-1
          ports:
            - containerPort: 5001
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
