apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: 241533151130.dkr.ecr.ap-southeast-1.amazonaws.com/service-2:latest
          ports:
            - containerPort: 5002
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
